### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by m-messiah** [TCP-Joker-BOT/TCPJoker#2]
Зачем писать велосипед в файле logger.py? Используй [logging](https://docs.python.org/3/howto/logging.html)

``` python
import logging
logging.basicConfig(filename='bot.log', level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
logging.info('info message')
```

**Comment by GoldsteinE** [comment]
Нет, не хочу.
Я знаю о logging и мне в данном случае удобней свой велосипед.

**Comment by m-messiah** [comment]
А можешь рассказать, почему? Я вот не увидел в logger.py такого убер-кода, который круче чем logging, отчего даже стало интересно - в какой ситуации он неудобен оказался.

**Comment by GoldsteinE** [comment]
Для меня так более удобно.
Мы живём в мире Open Source, хочешь что-то исправить -- отправляй Pull Request. Issue существуют для проблем в работе программы, а не в её коде.

**Comment by m-messiah** [comment]
Issue существуют как раз для вопросов в том числе. Не надо меня учить как гитхабом пользоваться.

Собственно, мне так-то пофиг на этого бота, особенно учитывая то, что я бы тут переписал 80% кода по своему, так что контрибьютить уж точно не собираюсь - своих дел полно.

Issues #2 , #3 , #4 были чисто из-за человеческого желания дать совет по написанию Python кода и улучшения мира в целом. Нет, так нет. Разговор можно закрыть.
