### ISSUE TITLE
CGI is bad

### ISSUE THREAD

**Issue by m-messiah** [TCP-Joker-BOT/TCPJoker#3]
С CGI уже даже в пхп не работают - сделай нормальный сервер на питоне и слушай запросы в нем. Так защитишься от всяких bash инъекций и оверхеда на запуска процесса на каждый запрос.

**Comment by GoldsteinE** [comment]
Если кто-то получил доступ к main.py это УЖЕ катастрофа, поэтому он хранится в трудновычислимой директории. Сервер на питоне вызовет кучу проблем с HTTPS и не сделает больше ничего. От bash-инъекций защищает свежий bash, запуск процесса на каждый запрос не страшен при включённом Privacy.

**Comment by m-messiah** [comment]
ШТА? Для https есть nginx.

А про всякие твои privacy почитай принципы CGI и почему от него отказываются в пользу FastCGI или пула процессов.

 Ну еще можно почитать про то, как процессы запускаются, и про проблему 10К

**Comment by GoldsteinE** [comment]
FastCGI резко сложнее реализовывать.
На github'е есть Pull request'ы, хочешь поправить -- создавай.
