### ISSUE TITLE
webhook ответ

### ISSUE THREAD

**Issue by m-messiah** [TCP-Joker-BOT/TCPJoker#4]
Телеграм понимает ответы на вебхук - если тебе пришел POST update с сообщением - ты можешь его обработать, а в ответ сделать json {'method': 'sendMessage', 'text': '...' и т д}, вместо инициации еще одного запроса отправки. (единственный минус - нет гарантии, что сообщение будет доставлено, потому что не узнаешь об ошибках, но это ты и сейчас не проверяешь)

**Comment by GoldsteinE** [comment]
А зачем?
Экономия траффика мизерная, если вообще есть.

**Comment by m-messiah** [comment]
1. Экономия запросов - экономия ресурсов (и это не только траффик)
2. Ты оставляешь делаешь лишнюю работу, завязанную на веб-запросы, отчего ответ прилетает дольше, чем надо (хоть это и не заметно на малых объемах)
3. Лишний код по формированию запроса и отправке его не сервер, вместо того, чтобы просто вернуть json в конце.

**Comment by GoldsteinE** [comment]
Окей, давай так -- на github'е есть Pull request'ы, хочешь поправить -- создавай.
